Componente SearchField
SoLanches/Frontend-SoLanches pull request #17
Opened 2021-07-30 20:28 UTC by LucianErick

Componente recebe via _props_ o texto do placeholder. Ao clicar no campo de input não há nenhum tipo de foco.

2021-07-31 00:42 UTC, RodrigoEC requested changes
Gostei bastante! Eu apontei algumas coisas nos comentários, mas tem algumas coisas também que vou apontar aqui:

- Coloca um placeholder no input, _"pesquisar"_ ou algo assim;
- Existem algumas coisas que estão causando warning no console do terminal, coisas simples mesmo, ajeita isso por favor;

⚠️ PS: Lembra de marcar o pessoal pra revisar, @marianasn @LeandraOS revisem por favor.

2021-07-31 00:42 UTC, RodrigoEC commented on src/Components/SearchField/index.jsx
> +import './styles.css';
Utiliza module.css

Dá uma pesquisada sobre o funcionamento de module.css, mas basicamente serve para empacotar o css dos componentes, aí não precisa colocar esses nomes gigantescos nas classes dos componentes.

2021-07-31 00:42 UTC, RodrigoEC commented on src/Components/SearchField/index.jsx
> +                <FiSearch size="1.5em" />
```suggestion
                <FiSearch size="1.5rem" />
```
O _em_ ele compara o tamanho da fonte com o tamanho da fonte da div que ele está presente, é melhor utilizar rem, o rem ele pega o tamanho da fonte root do projeto

2021-07-31 00:42 UTC, RodrigoEC commented on src/Components/SearchField/index.jsx
> +}
Adicionar espaço vazio no final do arquivo

2021-07-31 00:42 UTC, RodrigoEC commented on src/Components/SearchField/styles.css
> +}
Adicionar espaço vazio no final do arquivo

2021-07-31 00:44 UTC, LeandraOS commented
Além disso, é importante que ao fazer o pr a gente da equipe do front seja adicionada como Reviewers, assim somos notificados quando um novo componente ou funcionalidade é adicionada.

2021-07-31 00:46 UTC, LeandraOS commented
Outro ponto é vincular o número da issue com esse PR, assim quando o merge acontecer a issue será fechada automaticamente. 
Para fazer isso basta clicar em Linked issues e procurar pela issue alvo.

2021-07-31 00:47 UTC, LeandraOS commented
E por fim, é legal adicionar a tag "_enhancement_" ao PR.

2021-07-31 00:51 UTC, LeandraOS commented
É legal adicionar uma imagem do componente que foi desenvolvido para que possamos visualizá-lo também.

2021-07-31 17:16 UTC, LucianErick commented
![screenshot-localhost-3000-2021-07-31](https://user-images.githubusercontent.com/50140883/127747485-95b7f4af-b9c7-4b8f-b0ef-c7fc4e1e13ec.png)

O placeholder padrão passa a ser "Pesquisar", mas podendo ser alterado via _props_
Alteração na fonte do input de  _Inter_ para _Poppins_
Alteração no peso da fonte de 500 para 400

2021-07-31 22:27 UTC, RodrigoEC approved these changes

2021-08-01 05:38 UTC, LeandraOS approved these changes
:rocket:

2021-08-01 12:56 UTC, merged