Componente CheckCategory
SoLanches/Frontend-SoLanches pull request #18
Opened 2021-08-01 01:27 UTC by LucianErick

![screenshot-localhost-3000-2021-07-31 (1)](https://user-images.githubusercontent.com/50140883/127756170-098ac3e8-3769-4038-b6b3-d2b5086919ac.png)

Componente recebe, via _props_, o nome da categoria relacionada. Além disso, como considero todo o container como _label_, ao clicar no texto é possível selecionar e tirar a seleção da checkbox.
Outra característica posta intencionalmente é a impossibilidade do usuário selecionar (e arrastar pela tela) o texto que contém o nome da categoria.

2021-08-02 00:04 UTC, RodrigoEC commented
Ei, eu acho que seria legal a gente repensar esse design do checkbox...talvez algo mais cheinho e centralizado, tipo assim

![image](https://user-images.githubusercontent.com/42751604/127789211-38ad15b4-14a8-441a-aaad-6d2b84646176.png)

2021-08-02 00:08 UTC, RodrigoEC requested changes
A questão do código pra mim ta legal, mas como apontei no comentário acima acho que podemos repensar no design do componente

2021-08-02 12:29 UTC, LucianErick commented
![screenshot-localhost-3000-2021-08-02](https://user-images.githubusercontent.com/50140883/127861853-62fa8351-1f2a-42af-9f52-cf58dc8c5d76.png)

Como requisitado, com o objetivo de deixar a caixa mais preenchida, houve agora a centralização do check, além de um sutil aumento na espessura da borda da caixa.

2021-08-02 14:54 UTC, RodrigoEC approved these changes

2021-08-03 02:43 UTC, LeandraOS requested changes

2021-08-03 02:43 UTC, LeandraOS commented on src/Components/CheckCategory/styles.module.css
> +    border: 1.5px solid black;
Gostei bastante do código, e o componente está bem bonito. 
Porém, a cor está incorreta, ao invés de ser black a utilizada é a --primary-text: #314E52

2021-08-03 02:49 UTC, LeandraOS approved these changes
Gostei bastante do código, e o componente está bem bonito :rocket:
 
Porém, estou em dúvida em relação apenas a cor que eu acreditava que seria ao invés de ser black a utilizada seria a --primary-text: #314E52. Mas como está lá no figma como black, acredito que sigamos com ela mesmo. 

Se @RodrigoEC ou @marianasn  quiser opinar sobre isso, pode falar por aqui.

2021-08-03 22:56 UTC, merged