Feature category card
SoLanches/Frontend-SoLanches pull request #21
Opened 2021-08-03 01:20 UTC by LeandraOS

:pushpin: 

- [ X] Implementação do componente CategoryCard.

- [X ] Ao clicar no card a cor é alterada bem como a direção do ícone dropdown.

- [ X] Além disso, o componente conta com a sua versão responsiva

### Vídeo demonstrativo

<p align=center>
<img src="https://user-images.githubusercontent.com/50140771/127942706-dedf6df3-b19e-477e-b930-49cac2d7e990.gif"/>

2021-08-03 11:19 UTC, LucianErick approved these changes

2021-08-03 16:30 UTC, RodrigoEC requested changes
Apontei coisas para refatorar, mas para finalizar acho que seria legal colocar uma transição no componente, para que as transições de cor e rotation não sejam tão secas

2021-08-03 16:30 UTC, RodrigoEC commented on src/Components/CategoryCard/dropdown.jsx
> +function Dropdown(props) {
Esse componente é realmente necessário? A gente instalou a biblioteca [react-icons](https://react-icons.github.io/react-icons/) acho que nela existe um componente de dropdown, acho interessante apagar esse componente e utilizar o componente do React icons

2021-08-03 16:30 UTC, RodrigoEC commented on src/Components/CategoryCard/index.jsx
> +import './style.component.css'
Utilizar module.css para isolar as classes de css do componente, dá uma pesquisada em como usar, é bem simples

2021-08-03 16:30 UTC, RodrigoEC commented on src/Components/CategoryCard/index.jsx
> +function CategoryCard({title, imageUrl}) {
```suggestion
function CategoryCard({ title, imageUrl }) {
```

2021-08-03 16:30 UTC, RodrigoEC commented on src/Components/CategoryCard/index.jsx
> +    function toggle(){
Pela minha experiencia de React (que não é muita) geralmente essas funções de onClick a gente coloca o nome de "handleAlgumaCoisa". Seria tu interessante usar o useCallback inclusive
```suggestion
    const handleClick = usecallback(() => {
```

2021-08-03 16:30 UTC, RodrigoEC commented on src/Components/CategoryCard/index.jsx
> +        <div className={`${active ? "category-card" : "category-card-white"}`} >
Evitar atribuir nomes de classes que identificam quais propriedades ele atribui, como "white" por exemplo, uma vez que caso queiramos mudar essa propriedade nós teriamos que mudar o nome da classe, o que não é legal

Talvez uma boa mudança seja:

```suggestion
        <div className={`${active ? "category-card" : "category-card-active"}`} >
```

2021-08-03 16:30 UTC, RodrigoEC commented on src/Components/CategoryCard/index.jsx
> +                <div className="circle">
Evitar colocar propriedades nos nomes das classes

```suggestion
                <div className="images">
```

2021-08-03 16:30 UTC, RodrigoEC commented on src/Components/CategoryCard/index.jsx
> +            <p className={`${active ? "title" : "title-blue"}`}>{title}</p>
Essa questão do ativo, tu pode usar prioridades do css, dessa forma tu n precisa setar esse active aqui. Por exemplo se tu usar `.category-card-active .title` no css ele vai priorizar as propriedades que tu setar aqui

2021-08-03 16:30 UTC, RodrigoEC commented on src/Components/CategoryCard/index.jsx
> +export default CategoryCard
Adicionar linha vazia ao final do arquivo

2021-08-03 16:30 UTC, RodrigoEC commented on src/Components/CategoryCard/style.component.css
> +.category-card{
Seria legal tu adicionar uma classe geral do componente de categoria que possui todas essas propriedades que tu setou duras vezes no `category-card` e no `category-card-white` (mudar nome inclusive), aí tu adiciona outra classe de `active` talvez só pra setar a propriedade do card quando ele está ativo.

2021-08-03 16:30 UTC, RodrigoEC commented on src/Components/CategoryCard/style.component.css
> +}
Adicionar linha vazia no final do arquivo

2021-08-03 16:30 UTC, RodrigoEC commented on src/Components/CategoryCard/style.component.css
> +.dropdown__icon{
mudar nome para dropdown-icon ou dropdownIcon para manter um padrão de nomes

2021-08-03 16:30 UTC, RodrigoEC commented on src/Components/CategoryCard/style.component.css
> +    position: relative;
Esse position relative realmente precisa estar aqui? Pelo que eu entendi o componente não possui nada que fique fora da div para precisar desse position relative

2021-08-03 16:30 UTC, RodrigoEC commented on src/Components/CategoryCard/style.component.css
> +    overflow: hidden;
É necessário?

2021-08-03 16:30 UTC, RodrigoEC commented on src/Components/CategoryCard/style.component.css
> +    margin: 100px 100px 100px 100px;
Colocar margin: 100px já aplica o margin para todos os cantos
```suggestion
    margin: 100px;
```

2021-08-03 16:30 UTC, RodrigoEC commented on src/Components/CategoryCard/index.jsx
> +            <button className={`button-container ${active}`} onClick={toggle}>
Qual a necessidade desse botão? Não seria mais interessante que quando o usuário clique em qualquer parte do card ele ative, não?

2021-08-03 16:30 UTC, RodrigoEC commented on src/Components/CategoryCard/style.component.css
> +.button-container {
Classe desnecessária

2021-08-03 16:30 UTC, RodrigoEC commented on src/Components/CategoryCard/style.component.css
> +.circle{
Não utilizar propriedades de css para nomear classes

2021-08-03 16:30 UTC, RodrigoEC commented on src/App.js
> +      color='#fff'
Qual o motivo de passar a cor como uma prop?

2021-08-03 16:30 UTC, RodrigoEC commented on src/styles/App.css
> +   --color-base: #FFFFFF;
Se tu colocou o color-base aqui seria interessante refatorar o css das classes para utilizar o --color-base toda vez que for utilizar #FFF

2021-08-03 19:37 UTC, LeandraOS commented on src/Components/CategoryCard/index.jsx
> +import './style.component.css'
No último commit, eu usei o module.css, é bem ótimo mesmo!

2021-08-03 19:40 UTC, LeandraOS commented on src/App.js
> +      color='#fff'
Verdade, na minha implementação inicial fazia sentido.

2021-08-03 21:49 UTC, LeandraOS commented on src/Components/CategoryCard/dropdown.jsx
> +function Dropdown(props) {
Eu criei esse componente, pois eu consigo setar a cor dinamicamente, vou dar uma olhada nesses componentes do react e ver se eu consigo isso também.

2021-08-05 11:40 UTC, LucianErick approved these changes

2021-08-05 13:32 UTC, RodrigoEC approved these changes

2021-08-05 13:33 UTC, merged