Feature/button
SoLanches/Frontend-SoLanches pull request #24
Opened 2021-08-05 20:36 UTC by LeandraOS

## :pushpin: Implementação Button.

- [X] Ao passar o mouse a cor do button é alterada.
- [x] O título é recebido via props.
- [X] Além disso, o componente conta com a sua versão responsiva.

### :movie_camera: GIF demonstrativo
:warning: A cor que está no GIF está com bastante saturação, a cor real é bem mais clara.

<p align=center >
<img src="https://user-images.githubusercontent.com/50140771/128417238-a543d0db-f327-4fa3-800e-1a80bed7d82c.gif"/>

2021-08-05 20:47 UTC, RodrigoEC requested changes

2021-08-05 20:47 UTC, RodrigoEC commented on src/App.js
> +        <Button title="Cadastre-se"/>
trocar pelo Header de novo

2021-08-05 20:47 UTC, RodrigoEC commented on src/Components/Button/index.jsx
> +        <button className={style.container} onClick= "">
retirar esse onClick ja que ele não faz nada

2021-08-05 20:54 UTC, RodrigoEC approved these changes

2021-08-05 23:47 UTC, RodrigoEC approved these changes

2021-08-05 23:57 UTC, RodrigoEC approved these changes

2021-08-06 12:42 UTC, LucianErick approved these changes

2021-08-07 16:47 UTC, RodrigoEC commented
Tendo em vista a proposta de design apresentada por @LucianErick é interessante atualizar o botão para adicionar uma prop de ícone e adicionar a responsividade do botão para que dessa forma ele possa substituir o botão no componente criado por ele

2021-08-07 16:47 UTC, RodrigoEC requested changes
Apontei mudanças no comentário acima

2021-08-09 11:26 UTC, LucianErick commented on src/Components/Button/style.module.css
> +    margin: 8.88rem;
Provavelmente esse margin foi pra testar o componente, então pode tirar que fica top.

2021-08-09 13:10 UTC, LeandraOS commented on src/Components/Button/style.module.css
> +    margin: 8.88rem;
Verdade! Muito obrigada, vou tirar.

2021-08-10 10:33 UTC, LucianErick commented
Leandra, só mais uma coisa: Implementa esse botão no componente ServiceHours, por favor. Tem um comentário nesse componente feito por Rodrigo que ele pede isso...

2021-08-10 13:23 UTC, RodrigoEC commented
Na verdade eu coloquei aquele comentário pra integrar com esse componente que está sendo feito na verdade kkkkk eu coloque ali justamente pra eu não implementar o componente de outra pessoa de novo hehe

2021-08-10 13:46 UTC, RodrigoEC approved these changes

2021-08-10 19:35 UTC, LucianErick approved these changes

2021-08-10 20:00 UTC, merged