Componente CommerceInfo
SoLanches/Frontend-SoLanches pull request #26
Opened 2021-08-06 12:33 UTC by LucianErick

https://user-images.githubusercontent.com/50140883/128509347-ca1fb675-a2a2-4d36-9f4b-aae4d38fe234.mp4

- Houve algumas mudanças em relação ao design proposto pelo figma:
 1º: Espessura das bordar dos botões, ficando mais grossos e visíveis.
 2º: Aumento de padding interno dos botões de contato e horário, de forma a ficarem mais "cheios".
 3º Houve, também, a utilização de um ícone com espessura de borda maior para o botão de horário, ficando mais grosso, visível e padronizado de acordo com os outros.

- Houve o uso e  ligeiras mudanças no componente ServiceHours:
 1º: Nos textos "abre" e "fecha" e no botão de fechar houveram a mudança de cor para primary-text, invés de black.
 2º: No state de active, não sei por que, ao iniciar como false ele já iniciava com o modal aberto. Visto isso, alterei para _false_ para que o mesmo inicia-se apenas quando clicasse no botão.

- Em relação ao componente CommerceInfo, em si:
 1º: Achei interessante implementar que caso uma rede social não seja cadastrada, seu ícone não aparecerá. Como a única informação necessária relacionada a mídias sociais é o email, este é o único ícone obrigatório. 

**TODO**: Futuramente, talvez seja interessante implementar uma animação ao clicar no botão de horários, de modo que sua aparição não seja tão brusca.

2021-08-06 12:38 UTC, LucianErick commented
Uma coisa que esqueci de comentar acima foi a implementação da responsividade nos botões quando a tela chega num break-point de 320px. Nesse ponto o texto interno dos botões desaparece ficando só o ícone.

2021-08-06 18:06 UTC, LeandraOS commented on src/Components/CommerceInfo/styles.module.css
> +    width: 8.5rem;
Acredito que a imagem esteja grande de forma exagerada. Diminuir de forma que fique visível, mas ainda não tão grande vai ficar mais interessante.

2021-08-06 18:06 UTC, LeandraOS commented on src/Components/CommerceInfo/styles.module.css
> +}
Adicionar linha vazia ao final do arquivo.

2021-08-06 18:06 UTC, LeandraOS commented on src/Components/CommerceInfo/index.jsx
> +                <a href={social_medias.instagram} id={social_medias.instagram ? styles.social_icon : styles.none_icon}  >
Essa verificação pode ser feita utilizando useState de react, acredito que ficará mais interessante.

2021-08-06 18:06 UTC, LeandraOS commented on src/Components/CommerceInfo/index.jsx
> +export const CommerceInfo = ({ name, image, social_medias, address, phone, hours }) => {
Como o número de props é um pouco grande, não seria interessante usar o parâmetro como props e utilizar dentro do componente props.name, props.image e etc ?

2021-08-06 18:06 UTC, LeandraOS commented on src/Components/CommerceInfo/index.jsx
> +}
Adicionar linha ao final do arquivo.

2021-08-06 18:09 UTC, LeandraOS requested changes

2021-08-06 18:09 UTC, LeandraOS commented on src/Components/CommerceInfo/index.jsx
> +                    <AiOutlineInstagram color="314E52" size="1.5rem" />
Acredito que seja mais interessante usar os ícones colocados no design mesmo. Porque os ícones que estão no figma conversam melhor com o todo por ser mais minimalista.

2021-08-06 18:15 UTC, LeandraOS requested changes

2021-08-06 18:15 UTC, LeandraOS commented on src/Components/CommerceInfo/index.jsx
> +export const CommerceInfo = ({ name, image, social_medias, address, phone, hours }) => {
Como o número de props é um pouco grande, não seria interessante usar o parâmetro como props e utilizar dentro do componente props.name, props.image e etc ?

2021-08-06 18:15 UTC, LeandraOS commented on src/Components/CommerceInfo/index.jsx
> +                <a href={social_medias.instagram} id={social_medias.instagram ? styles.social_icon : styles.none_icon}  >
Essa verificação pode ser feita utilizando useState de react, acredito que ficará mais interessante.

2021-08-06 18:15 UTC, LeandraOS commented on src/Components/CommerceInfo/index.jsx
> +                    <AiOutlineFacebook color="314E52" size="1.5rem" />
Acredito que seja mais interessante usar os ícones colocados no design mesmo. Porque os ícones que estão no figma conversam melhor com o todo por ser mais minimalista.

2021-08-06 18:15 UTC, LeandraOS commented on src/Components/CommerceInfo/index.jsx
> +                    <AiOutlineMail color="314E52" size="1.5rem" id={styles.social_icon} />
Acredito que seja mais interessante usar os ícones colocados no design mesmo. Porque os ícones que estão no figma conversam melhor com o todo por ser mais minimalista. Esse item também está desalinhado em relação aos demais.

2021-08-06 18:15 UTC, LeandraOS commented on src/Components/CommerceInfo/index.jsx
> +}
Adicionar linha ao final do arquivo.

2021-08-06 18:15 UTC, LeandraOS commented on src/Components/CommerceInfo/styles.module.css
> +    color: #314E52;
É interessante utilizar as variáveis criadas.
Recomendo trocar a cor pela var(--primary-text)

2021-08-06 18:15 UTC, LeandraOS commented on src/Components/CommerceInfo/styles.module.css
> +    width: 8.5rem;
Acredito que a imagem esteja grande de forma exagerada. Diminuir de forma que fique visível, mas ainda não tão grande vai ficar mais interessante.

2021-08-06 18:15 UTC, LeandraOS commented on src/Components/CommerceInfo/styles.module.css
> +    padding: 0.7rem 1rem;
Acredito que o espaço interno desses dois buttons centrais estão bem enormes e quebra bastante o design que vem sendo minimalista. Entendo a proposta de trazer ainda mais visibilidade, mas o espaço atual está ao meu ver exagerado. Diminuir o padding será bastante interessante.

2021-08-06 18:15 UTC, LeandraOS commented on src/Components/CommerceInfo/styles.module.css
> +    color: white;
É interessante fazer uso da variável --color-base

2021-08-06 18:15 UTC, LeandraOS commented on src/Components/CommerceInfo/styles.module.css
> +    background-color: #ff8011;
Para uniformizar a cor do hover dos buttons, eu utilizei a seguinte cor que está na varíavel --color-effect: #FC8621; Então acredito que seria legal você utilizar para que tudo esteja conciso.

2021-08-06 18:15 UTC, LeandraOS commented on src/Components/CommerceInfo/styles.module.css
> +}
Adicionar linha vazia ao final do arquivo.

2021-08-06 18:17 UTC, LeandraOS commented
> Uma coisa que esqueci de comentar acima foi a implementação da responsividade nos botões quando a tela chega num break-point de 320px. Nesse ponto o texto interno dos botões desaparece ficando só o ícone.

Achei isso bastante legal, ficou bem interessante mesmo.

2021-08-07 16:43 UTC, RodrigoEC commented on src/Components/CommerceInfo/index.jsx
> +export const CommerceInfo = ({ name, image, social_medias, address, phone, hours }) => {
Concordo

2021-08-11 14:14 UTC, RodrigoEC requested changes
Tudo bem legal, mas precisa resolver os problemas do linter apontados pelo navegador

2021-08-16 02:37 UTC, LeandraOS approved these changes

2021-08-18 13:44 UTC, RodrigoEC approved these changes

2021-08-18 13:44 UTC, merged