Feature de upload de foto do perfil
SoLanches/Frontend-SoLanches pull request #27
Opened 2021-08-08 14:01 UTC by marianasn

![simplescreenrecorder-2021-08-08_10 40 33 (1)](https://user-images.githubusercontent.com/38408320/128634358-14ce7a49-09d7-4728-b057-32d6575c94d0.gif)

- O componente de upload da imagem do perfil carrega a foto para que o usuário possa ver o preview da imagem. Se ele não gostar de como a imagem ficou, ele pode carregar outras imagens até que fique satisfeito com o que vê no preview.  
- OBS: não me preocupei muito com a borda branca, como acontece na segunda imagem, porque, geralmente, logos de comércios são png com fundo branco.

2021-08-08 17:54 UTC, RodrigoEC requested changes
Gostei muito! Mas acho que em telas mobile o círculo está muito grande, seria legal adiicionar responsividade para essas telas, deixando o circulo um pouco menor

2021-08-08 17:54 UTC, RodrigoEC commented on src/Components/ProfileImage/style.module.css
> +}
Adicionar linha vazia no final do arquivo

2021-08-08 18:36 UTC, marianasn commented on src/Components/ProfileImage/style.module.css
> +}
Verdade! Vou fazer o component responsivo

2021-08-09 00:11 UTC, marianasn commented on src/Components/ProfileImage/style.module.css
> +}
Adicionei a responsividade, vê se tá ok. Se quiser menor ou maior, só avisar :D

2021-08-09 03:55 UTC, LeandraOS requested changes

2021-08-09 03:55 UTC, LeandraOS commented on src/Components/ProfileImage/index.jsx
> +    const handleImageUpload = (e) => {
Esse "e" seria o que?  Talvez seria interessante colocar um nome mais representativo :rocket:

2021-08-09 03:55 UTC, LeandraOS commented on src/Components/ProfileImage/index.jsx
> +}
Adicionar linha ao final do arquivo

2021-08-09 03:55 UTC, LeandraOS commented on src/Components/ProfileImage/style.module.css
> +.profileImage{
Como não há nenhum uso de css, acredito que poderia ser retirada do arquivo e da tag essa classe

2021-08-09 04:15 UTC, LeandraOS requested changes

2021-08-09 04:15 UTC, LeandraOS commented on src/Components/ProfileImage/style.module.css
> +    border: 1px #314E52 solid;
No arquivo App.css temos as definições de cores. Com isso, recomendo que você ao invés de utilizar a cor utilize a variável.
color: var(--primary-text)

2021-08-11 19:58 UTC, marianasn commented on src/Components/ProfileImage/index.jsx
> +    const handleImageUpload = (e) => {
"e" é de element, é um padrão de javascript utilizar o "e", ou "el" ou "element"

2021-08-11 20:00 UTC, marianasn commented on src/Components/ProfileImage/style.module.css
> +    border: 1px #314E52 solid;
Não tinha visto isso, vou alterar! :D

2021-08-12 10:24 UTC, LucianErick approved these changes

2021-08-13 02:34 UTC, LeandraOS approved these changes

2021-08-24 22:17 UTC, RodrigoEC approved these changes

2021-08-24 22:17 UTC, merged