Feature de card de configurações de um comercio
SoLanches/Frontend-SoLanches pull request #28
Opened 2021-08-08 23:55 UTC by marianasn

https://user-images.githubusercontent.com/38408320/128649332-38a04da1-9f8e-456e-a548-a8fb9743f643.mp4

- Utilizei o ant design pros componentezinhos, dois deles eu não consegui encontrar um idêntico ao do design no figma (o de listar os itens e a lixeira para excluir categoria).
- Deixei os links nas opções de editar, adicionar, remover e etc, para acessar as páginas futuras. 
- Não consegui diminuir os componentes de engrenagem e o X ao fazer a responsividade da tela.

2021-08-09 04:13 UTC, LeandraOS requested changes

2021-08-09 04:13 UTC, LeandraOS commented on src/Components/CommerceCategoryCard/index.jsx
> +                :
Esses ":" tem alguma utilidade ?

2021-08-09 04:13 UTC, LeandraOS commented on src/Components/CommerceCategoryCard/index.jsx
> +
Retirar dois espaços e adicionar espaço ao final do arquivo

2021-08-09 04:13 UTC, LeandraOS commented on src/Components/CommerceCategoryCard/style.module.css
> +    color: #909090;
Adicionar css para a hr, no design do figma a linha é bem mais fina, com isso, recomendo utilizar o seguinte css para fazer isso:
`border-top: 0.5px solid #909090 ;`

2021-08-09 04:13 UTC, LeandraOS commented on src/Components/CommerceCategoryCard/style.module.css
> +    width: 100%;
A linha proposta pelo design não vai até o final da width do componente, então acredito que se você utilizar 90% ou 95% de width pode ficar bem legal :rocket:

2021-08-09 04:13 UTC, LeandraOS commented on src/Components/CommerceCategoryCard/style.module.css
> +
Retirar linha e adicionar linha ao final do arquivo

2021-08-09 04:13 UTC, LeandraOS commented on src/Components/CommerceCategoryCard/style.module.css
> +
retirar linha

2021-08-09 04:13 UTC, LeandraOS commented on src/Components/CommerceCategoryCard/style.module.css
> +    color: #FF983B;
No arquivo App.css temos as definições de cores. Com isso, recomendo que você ao invés de utilizar a cor utilize a variável.
`color: var(--primary-color)`

2021-08-09 04:13 UTC, LeandraOS commented on src/Components/CommerceCategoryCard/style.module.css
> +    color: #314E52;
No arquivo App.css temos as definições de cores. Com isso, recomendo que você ao invés de utilizar a cor utilize a variável.
color: var(--primary-text)

2021-08-09 04:13 UTC, LeandraOS commented on src/Components/CommerceCategoryCard/style.module.css
> +    color: #314E52;
No arquivo App.css temos as definições de cores. Com isso, recomendo que você ao invés de utilizar a cor utilize a variável.
color: var(--primary-text)

2021-08-09 04:13 UTC, LeandraOS commented on src/Components/CommerceCategoryCard/style.module.css
> +    color: #909090;
No arquivo App.css pode-se criar uma variável para esta cor, já que ela vem sendo bastante utilizada.

2021-08-09 04:13 UTC, LeandraOS commented on src/Components/CommerceCategoryCard/style.module.css
> +    background-color: white;
No arquivo App.css temos as definições de cores. Com isso, recomendo que você ao invés de utilizar a cor utilize a variável.
color: var(--color-base)

2021-08-09 04:13 UTC, LeandraOS commented on src/Components/CommerceCategoryCard/style.module.css
> +    color: #314E52;
No arquivo App.css temos as definições de cores. Com isso, recomendo que você ao invés de utilizar a cor utilize a variável.
color: var(--primary-text)

2021-08-09 18:10 UTC, marianasn commented on src/Components/CommerceCategoryCard/index.jsx
> +                :
Sim, amiga, é um "else"

2021-08-09 19:58 UTC, LeandraOS commented on src/Components/CommerceCategoryCard/index.jsx
> +                :
Ah simm, muito massa!

2021-08-12 10:23 UTC, LucianErick approved these changes

2021-08-16 02:25 UTC, LeandraOS requested changes

2021-08-16 02:25 UTC, LeandraOS commented on src/Components/CommerceCategoryCard/style.module.css
> +.categoryOptions hr{
A alteração para o primeiro card funcionou muito bem! 
Porém, no card que tem as opções a linha ainda continua escura e larga. 
O mesmo está acontecendo para o componente para mobile. 

Se todas as linhas ficarem na cor clara e fina, vai ficar legal <3

2021-08-19 02:13 UTC, marianasn commented on src/Components/CommerceCategoryCard/style.module.css
> +.categoryOptions hr{
Mas nas duas eu coloquei a mesma configuração:  
    width: 95%;
    border-top: 0.5px solid var(--gray-base);
e ela não muda quando a tela muda pra 550px. O css tá ok, testei aqui e não vi nenhuma diferença entre o card das opções

2021-08-21 01:28 UTC, LeandraOS approved these changes

2021-08-21 01:32 UTC, merged