CardCommerce
SoLanches/Frontend-SoLanches pull request #29
Opened 2021-08-11 03:12 UTC by LeandraOS

## :pushpin: Implementação CardCommerce.

- [X] Ao passar o mouse há um efeito discreto de zoom.
- [x] O título, ícone, endereço e três opções de horários (há a opção de passar apenas um horário, dois, ou três) são recebidos via props.
- [X] Além disso, o componente conta com as suas versões responsivas.

### :watch: Tempo utilizado para desenvolvimento

- 4 horas

### :page_facing_up:  Forma de uso 
`<CardCommerce icon= "./assets/icons/exemplo.svg" title="Hamburgueria Lá em Robson" adress= "Rua Celso Cirne, 449 - Solânea " time=" Seg, qua, qui e sex : 14h - 23h" timeTwo="Sáb e dom: 17h - 23h" timeTwo= " "/>`

### :movie_camera: Vídeo demonstrativo

https://user-images.githubusercontent.com/50140771/128963485-342d04b5-8bde-44fd-916e-b86207f43646.mp4

2021-08-24 22:16 UTC, LucianErick requested changes

2021-08-24 22:16 UTC, LucianErick commented on src/Components/CardCommerce/style.module.css
> +
Retirar espaços vazios no meio das classes. Como a maioria dos itens não tem eles, fica interessante padronizar...

2021-08-24 22:16 UTC, LucianErick commented on src/Components/CardCommerce/index.jsx
> +                        <p className={style.times}>{props.time}</p>
Para evitar essa repetição, não seria mais viável receber a lista de horários via _props_ (sugestão: _props.schedule_) e percorrê-la usando _props.schedule.map()_?

2021-08-26 11:19 UTC, RodrigoEC approved these changes

2021-08-26 23:11 UTC, LucianErick approved these changes

2021-08-26 23:15 UTC, merged