Feature Login Card
SoLanches/Frontend-SoLanches pull request #30
Opened 2021-08-12 15:20 UTC by LucianErick

https://user-images.githubusercontent.com/50140883/129221745-d803e2a0-d9d2-4e02-af01-96f6659878c2.mp4

- Tempo para desenvolvimento: 4 horas

### Modo de usar
`<LoginCard />`

### TODO: 
- Futuramente, quando as páginas de recuperar senha e cadastrar forem feitas, vai ter que apontar as rotas.
- De qualquer modo, futuramente vai precisar integrar com a API.

2021-08-16 02:32 UTC, LeandraOS requested changes
Achei o código muito bom! :rocket: 

Apontei alguns detalhes mais de questão de organização do código.

2021-08-16 02:32 UTC, LeandraOS commented on src/Components/CommerceInfo/index.jsx
> +}
Adicionar linha ao final do arquivo :rocket:

2021-08-16 02:32 UTC, LeandraOS commented on src/Components/CommerceInfo/styles.module.css
> +
Retirar linha a mais.

2021-08-16 02:32 UTC, LeandraOS commented on src/Components/CommerceInfo/styles.module.css
> +}
Adicionar linha ao final do arquivo :rocket:

2021-08-16 02:32 UTC, LeandraOS commented on src/Components/LoginCard/index.jsx
> +}
Adicionar linha ao final do arquivo :rocket:

2021-08-16 02:32 UTC, LeandraOS commented on src/Components/LoginCard/styles.module.css
> +    background-color: #FFFFFF;
Temos as variáveis de cores no App.css. É interessante utilizar a variável --color-base.

2021-08-16 16:02 UTC, LucianErick commented on src/Components/LoginCard/index.jsx
> +}
Essas linhas nos finais do arquivo já existem..

![Captura de tela de 2021-08-16 13-01-28](https://user-images.githubusercontent.com/50140883/129593683-6877e65e-fdd9-4389-9363-ea912dd2216a.png)

2021-08-17 21:29 UTC, LeandraOS approved these changes

2021-08-18 13:43 UTC, RodrigoEC approved these changes

2021-08-18 13:43 UTC, RodrigoEC commented on src/Components/CommerceInfo/index.jsx
> +export const CommerceInfo = (props) => {
Qual o motivo desse componente estar aqui? A PR não é para adicionar componente de LoginCard?

2021-08-18 13:45 UTC, merged