Adiciona componente RegisterSchedule
SoLanches/Frontend-SoLanches pull request #45
Opened 2021-09-06 13:54 UTC by RodrigoEC

## Descrição
A PR adiciona o componente RegisterSchedule, o componente serve para o estabelecimento ao se registrar ele conseguir registrar também o horário de atendimento do seu estabelecimento.

### Como utilizar
```javaScript
import RegisterSchedules from '~/Components/RegisterSchedules
<RegisterSchedules />
```
### Vídeo descritivo

https://user-images.githubusercontent.com/42751604/132227802-dc0095e0-9899-4f1b-96ad-8b3a504ef770.mp4

2021-09-06 16:11 UTC, LucianErick approved these changes

2021-09-07 01:31 UTC, LeandraOS requested changes
Eu achei o código ótimo, comentei apenas sobre a falta da linha ao final do arquivo, após essa modificação já estará pronto para ser merjado :rocket:

2021-09-07 01:31 UTC, LeandraOS commented on src/styles/App.css
> -
Falta de linha ao final do arquivo.

2021-09-07 20:02 UTC, RodrigoEC commented on src/styles/App.css
> -
Essa é a versão antiga do código kk

2021-09-07 20:03 UTC, RodrigoEC commented on src/styles/App.css
> -
Essa é a versão antiga do código kk

2021-09-09 19:00 UTC, LeandraOS approved these changes

2021-09-09 19:07 UTC, merged