Refatora componente de header para se adaptar as mudanças feitas com relação a login
SoLanches/Frontend-SoLanches pull request #77
Opened 2021-09-21 23:52 UTC by RodrigoEC

### Descrição 

Refatora componente `Header` para adicionar modal de login e rota de meu perfil, assim como melhoria no design mobile

### Screenshot do componente

![image](https://user-images.githubusercontent.com/42751604/134262375-ef1d109c-60bc-49a4-a01f-b317459ca38d.png)

2021-09-22 01:25 UTC, LeandraOS requested changes

2021-09-22 01:25 UTC, LeandraOS commented on src/Components/LoginCard/styles.module.css
> +  color: #909090;
Como temos a varíavel --gray-base no arquivo App.css seria melhor utilizá-la :)

2021-09-22 14:31 UTC, LeandraOS approved these changes
:rocket:

2021-09-25 12:23 UTC, LucianErick approved these changes

2021-09-26 02:00 UTC, merged