Feature/categories commerces
SoLanches/Frontend-SoLanches pull request #78
Opened 2021-09-22 00:15 UTC by LeandraOS

## :pushpin: Implementação tela de categorias.

- [X] Ao clicar no card referente à uma categoria os comércios que pertencem aquela dada categoria são listados.
- [X] Além disso, a tela e os componentes contam com as suas versões responsivas.

### :watch: Tempo utilizado para desenvolvimento

- 8 horas

### :movie_camera: Vídeo demonstrativo

https://user-images.githubusercontent.com/50140771/134263788-58eaccf5-e935-4f4f-9173-7ec3b4fd45c3.mp4

2021-09-22 11:59 UTC, LucianErick approved these changes

2021-09-22 12:21 UTC, RodrigoEC commented
Resolver problemas de linter apontados n console, isso é necessário para fazer o deploy.

2021-09-22 12:25 UTC, RodrigoEC requested changes
Arrasou, só vou pedir pra tu resolver os problemas que o navegador apontou na aba de console. Se tiver algum problema assim o vercel não permite que nós façamos o deploy

2021-09-25 20:36 UTC, RodrigoEC approved these changes

2021-09-25 22:10 UTC, merged