Páginas de Cadastro
SoLanches/Frontend-SoLanches pull request #79
Opened 2021-09-22 13:27 UTC by LucianErick

- Página de cadastro inicial
- [x] - Validação dos dados
- [x] - Máscara de input para cnpj e telefone 

- Página de cadastro de horários
- [x] - Adição e alteração dos horários dinamicamente
- [x] - Tratamento para caso o número de horários exceda um limite de 7 horários e caso o usuário tente adicionar um horário antes de preencher algum anterior

- Página de cadastro de foto
Obs: A imagem que salvo é padrão, independente do que o usuário insere.

- Página de cadastro de categorias
- [x] - Adição e remoção dinâmica de categorias
- [x] - Requisição ao servidor para cadastro
- [x] - Validação caso o usuário tente registrar sem passar nenhuma categoria
- [x] - Modal exibido e redirecionado para página inicial para indicar cadastro realizado

-[x] Alteração dinâmica entre as páginas com os botões avançar e voltar/cancelar.  

https://user-images.githubusercontent.com/50140883/134351361-a2d3f8ba-9a58-48e5-80db-3e92fd11c5c1.mp4

2021-09-22 19:47 UTC, RodrigoEC commented
Falta adicionar a rota de registrar, ela existe no vídeo, mas não na PR, adiciona la e a chave/valor "header: false" no objeto como dos outros pra ele n aparecer no header

2021-09-23 16:17 UTC, RodrigoEC commented
Luciando, o registro de um comércio não está funcionando, dá o status code 400. Além disso, existe um console.log

2021-09-23 19:09 UTC, LucianErick commented
> Luciando, o registro de um comércio não está funcionando, dá o status code 400. Além disso, existe um console.log

Quanto ao console.log() eu acabei de retirar, obrigado por me lembrar :)

Em relação ao erro 400 ao cadastrar: tens certeza que testasse com a branch atualizada? Testei aqui agora e deu certo. Inclusive, teu um teste teu no bd

![Captura de tela de 2021-09-23 15-59-37](https://user-images.githubusercontent.com/50140883/134568391-04ed1ff5-eedf-4663-909f-237b6a6f522a.png)

![Captura de tela de 2021-09-23 16-02-28](https://user-images.githubusercontent.com/50140883/134568397-ede9f376-4a7d-4e51-917f-6e81187e8537.png)

- Porém, me estranha o fato do campo endereço, nesse teu teste, vir com um hash, não com uma informação

2021-09-25 20:34 UTC, LeandraOS requested changes

2021-09-25 20:34 UTC, LeandraOS commented on src/App.js
> +export default App;
Adicionar linha :smiley:

2021-09-25 20:34 UTC, LeandraOS commented on src/Components/CheckCategory/index.jsx
> +        <div className={styles.container} onClick={handleSelect}>
Alterar o lugar onde  click acontece, pois atualmente só conseguimos assinalar ou ativar o check ao clicar no nome da categoria e não no check-box.

2021-09-25 20:34 UTC, LeandraOS commented on src/contexts/register.context.js
> +}
adicionar uma linha.

2021-09-25 20:34 UTC, LeandraOS commented on src/pages/Register/Initial/index.jsx
> +              placeholder="intragram.com/SoLanches"
Alterar "intagram" para "instagram"

2021-09-25 20:34 UTC, LeandraOS commented on src/pages/Register/Schedule/index.jsx
> +        "Erro ao adiconar horário",
Trocar "adiconar" para adicionar

2021-09-25 20:34 UTC, LeandraOS commented on src/pages/Register/Schedule/index.jsx
> +          estabelecimento
Adicionar um ponto ao final da frase

2021-09-25 20:34 UTC, LeandraOS commented on src/pages/Register/Schedule/index.jsx
> +        "Erro ao adiconar horário",
Mudar a cor desse texto, para vermelho.

2021-09-25 20:34 UTC, LeandraOS commented on src/pages/Register/steps.jsx
> +
remover linha 3

2021-09-25 20:34 UTC, LeandraOS commented on src/pages/Register/Initial/index.jsx
> +            <label htmlFor="name">Nome</label>
Adicionar o * vermelho onde o campo for obrigatório

2021-09-25 20:34 UTC, LeandraOS commented on src/pages/Register/Initial/index.jsx
> +            <label htmlFor="name">Nome</label>
Criar variável para o vermelho, pois ele será utilizado aqui e no card que comentei mais abaixo.

2021-09-25 20:34 UTC, LeandraOS commented on src/services/api.js
> +    console.log(e);
retirar `console.log(e)`

2021-09-25 20:34 UTC, LeandraOS commented on src/services/api.js
> +    console.log(e);
retirar `console.log(e)`

2021-09-25 20:34 UTC, LeandraOS commented on src/services/api.js
> +    console.log(e);
retirar `console.log(e)`

2021-09-25 20:34 UTC, LeandraOS commented on src/services/api.js
> +    console.log(e);
retirar `console.log(e)`

2021-09-25 20:34 UTC, LeandraOS commented on src/services/api.js
> -    console.log(e)
retirar o `console.log(e)`

2021-09-25 20:34 UTC, LeandraOS commented on src/services/api.js
> +};
adicionar linha

2021-09-26 14:05 UTC, LucianErick commented
### Melhorias aplicadas

- [x] Inserção de caractere '*' na cor vermelha nos campos obrigatórios na página inicial de cadastro
- [x] Validação do avanço na página de horários sem antes ter preenchido os horários
- [x] Correção de problemas de digitação
- [x] Retirada dos múltiplos console.log()
- [x] Centralização dos botões em telas mobile
- [x] Correção de bug do selecionar categorias, agora permitindo ao usuário clicar dentro do checkbox
- [x] Inserção do ponto final no header das páginas



https://user-images.githubusercontent.com/50140883/134811156-e53b0f11-3aa6-4249-bfed-f13d856a5b96.mp4

2021-09-26 14:22 UTC, LucianErick commented
##Importante frisar:

Ao mexer nessa branch, é necessário fazer o `yarn install` novamente, pois houve a adição dos pacotes

2021-09-27 12:21 UTC, LucianErick commented
Outra adição que achei interessante colocar foi a estilização da barra de scroll. Na minha opinião ficou bonito.

![Captura de tela de 2021-09-27 09-17-54](https://user-images.githubusercontent.com/50140883/134906846-808ba57d-0e2d-477d-afc7-4184f8f608e1.png)

2021-09-27 15:55 UTC, RodrigoEC approved these changes

2021-09-27 16:13 UTC, LeandraOS approved these changes

2021-09-27 16:13 UTC, merged